filename: "{{.InterfaceName | snakecase}}.go"
structname: "Mock{{.InterfaceName | firstUpper}}"
dir: "{{.InterfaceDir}}/mocks/"
pkgname: "mocks"
packages:
  gitlab.education.tbank.ru/backend-academy-go-2025/homeworks/hw2-labyrinths/internal/application:
    interfaces:
      Generator:
      Solver: