// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"gitlab.education.tbank.ru/backend-academy-go-2025/homeworks/hw2-labyrinths/internal/domain/entities"
	"gitlab.education.tbank.ru/backend-academy-go-2025/homeworks/hw2-labyrinths/internal/domain/maze"
)

// NewMockSolver creates a new instance of MockSolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSolver {
	mock := &MockSolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSolver is an autogenerated mock type for the Solver type
type MockSolver struct {
	mock.Mock
}

type MockSolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSolver) EXPECT() *MockSolver_Expecter {
	return &MockSolver_Expecter{mock: &_m.Mock}
}

// Solve provides a mock function for the type MockSolver
func (_mock *MockSolver) Solve(m *maze.Maze, start *entities.Cell, end *entities.Cell) (*entities.Path, bool) {
	ret := _mock.Called(m, start, end)

	if len(ret) == 0 {
		panic("no return value specified for Solve")
	}

	var r0 *entities.Path
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(*maze.Maze, *entities.Cell, *entities.Cell) (*entities.Path, bool)); ok {
		return returnFunc(m, start, end)
	}
	if returnFunc, ok := ret.Get(0).(func(*maze.Maze, *entities.Cell, *entities.Cell) *entities.Path); ok {
		r0 = returnFunc(m, start, end)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Path)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*maze.Maze, *entities.Cell, *entities.Cell) bool); ok {
		r1 = returnFunc(m, start, end)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockSolver_Solve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Solve'
type MockSolver_Solve_Call struct {
	*mock.Call
}

// Solve is a helper method to define mock.On call
//   - m *maze.Maze
//   - start *entities.Cell
//   - end *entities.Cell
func (_e *MockSolver_Expecter) Solve(m interface{}, start interface{}, end interface{}) *MockSolver_Solve_Call {
	return &MockSolver_Solve_Call{Call: _e.mock.On("Solve", m, start, end)}
}

func (_c *MockSolver_Solve_Call) Run(run func(m *maze.Maze, start *entities.Cell, end *entities.Cell)) *MockSolver_Solve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *maze.Maze
		if args[0] != nil {
			arg0 = args[0].(*maze.Maze)
		}
		var arg1 *entities.Cell
		if args[1] != nil {
			arg1 = args[1].(*entities.Cell)
		}
		var arg2 *entities.Cell
		if args[2] != nil {
			arg2 = args[2].(*entities.Cell)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSolver_Solve_Call) Return(path *entities.Path, b bool) *MockSolver_Solve_Call {
	_c.Call.Return(path, b)
	return _c
}

func (_c *MockSolver_Solve_Call) RunAndReturn(run func(m *maze.Maze, start *entities.Cell, end *entities.Cell) (*entities.Path, bool)) *MockSolver_Solve_Call {
	_c.Call.Return(run)
	return _c
}
